plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}.forge.mixins.json")
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = true

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }
    def genResources = project(':common').file('src/generated/resources')
    def atResources = project(':common').file('src/main/resources')
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        client {
            client()
        }
        data {
            data()
            programArguments.addAll "--all", "--mod", "trading_floor"
            programArguments.addAll "--output", genResources.absolutePath
            programArguments.addAll "--existing", atResources.absolutePath
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir project(":common").file('src/generated/resources')

repositories {
    maven {
        url = "https://maven.tterrag.com/"
        content {
            includeGroup("com.tterrag.registrate")
            includeGroup("com.simibubi.create")
        }
    }
    maven { url = "https://maven.createmod.net/" }
}

dependencies {
//    compileOnly project(":common")
//    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")

    compileOnly ("com.simibubi.create:create-${minecraft_version}:${create_version}")
    compileOnly (("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}"))
    compileOnly (("dev.engine-room.flywheel:flywheel-forge-api-${minecraft_version}:${flywheel_version}"))
    compileOnly (("com.tterrag.registrate:Registrate:${registrate_version}"))
    compileOnly ("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")


    modImplementation ("com.simibubi.create:create-${minecraft_version}:${create_version}")
    modImplementation (("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}"))
    modImplementation (("dev.engine-room.flywheel:flywheel-forge-api-${minecraft_version}:${flywheel_version}"))
    modImplementation (("com.tterrag.registrate:Registrate:${registrate_version}"))
    modImplementation ("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")

}

jar {
    finalizedBy('reobfJar')
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    ])
}